# Generated by Django 2.2.24 on 2021-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='images/gallerie/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
