# Generated by Django 2.2.24 on 2021-08-31 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0002_auto_20210831_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='créer par '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='evangelisation',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='remplissages.Evangelisation', verbose_name='Évangelsation du '),
            preserve_default=False,
        ),
    ]
